apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: servicio-pagos
  description: Servicio responsable de procesar transacciones financieras y tarjetas.
  annotations:
    # Esta anotación es crucial para que el Discovery Provider de GitHub lo encuentre
    github.com/project-slug: mi-organizacion/repo-servicio-pagos
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - spring-boot
    - critical
  links:
    - title: Dashboard de Grafana
      url: https://grafana.mi-empresa.com/d/payments
spec:
  type: service
  lifecycle: production
  owner: equipo-financiero
  system: plataforma-ecommerce
  # Este servicio PROVEE una API que otros consumen
  providesApi:
    - nombre: pagos-api-v1
      description: API REST para procesar cobros